[package]
name = "snapshot_redactions"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
insta = { workspace = true, features = ["json", "redactions"] }
serde_json = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"] }
