[package]
name = "tempfile_tempdir"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-manifest = "0.19"
cargo-util-schemas = "0.7.1"
toml = "0.8.19"

[dev-dependencies]
googletest = { workspace = true }
tempfile = { workspace = true }
